services:

  fluent-bit:
    image: fluent/fluent-bit:latest
    container_name: fluent-bit
    command: -c /fluent-bit/etc/fluent-bit.yaml
    volumes:
      - ./logs:/logs
      - ./fluent-bit.yaml:/fluent-bit/etc/fluent-bit.yaml

  loki:
    image: grafana/loki:2.9.0
    ports:
      - "3100:3100"
    volumes:
      - ./loki-config.yaml:/etc/loki/local-config.yaml
    command: -config.file=/etc/loki/local-config.yaml
    depends_on:
    - fluent-bit