[INPUT]
    Name tail
    Path /logs/logcat.log
    Tag logcat

[INPUT]
    Name tail
    Path /logs/appium.log
    Tag appium

[INPUT]
    Name tail
    Path /logs/gaf.log
    Tag gaf

[OUTPUT]
    Name opensearch
    Match *
    Host opensearch
    Port 9200
    Index gaf-logs