[SERVICE]
    Flush 1
    Daemon Off

[INPUT]
    Name tail
    Path /logs/gaf.log
    Tag gaf

[INPUT]
    Name tail
    Path /logs/appium.log
    Tag appium

[INPUT]
    Name tail
    Path /logs/logcat.log
    Tag logcat

[OUTPUT]
    Name loki
    Match *
    Host loki
    Port 3100
    Labels job=testlogs